[build]
  command = "yarn build && cd functions/apollo-graphql && yarn"
  functions = "functions"
  publish = "public/"
[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''